import os
from pathlib import Path

from dotenv import load_dotenv


load_dotenv(Path(__file__).with_name(".env"))


def env_bool(name, default="False"):
    return os.getenv(name, default).strip().lower() == "true"


def env_int(name, default):
    value = os.getenv(name)
    return int(value) if value not in (None, "") else default


def env_float(name, default):
    value = os.getenv(name)
    return float(value) if value not in (None, "") else default


def env_float_list(name, default):
    value = os.getenv(name)

    if value in (None, ""):
        return default

    result = []

    for item in value.split(","):
        item = item.strip()

        if item:
            result.append(float(item))

    return result or default


API_KEY = os.getenv("API_KEY")
SECRET_KEY = os.getenv("SECRET_KEY")

SYMBOLS = [
    symbol.strip()
    for symbol in os.getenv("SYMBOLS", "").split(",")
    if symbol.strip()
]

# Long-term mode: 1d trend, 4h confirmation, 1h entry timing.
TREND_TIMEFRAME = os.getenv("TREND_TIMEFRAME", "1d")
CONFIRMATION_TIMEFRAME = os.getenv("CONFIRMATION_TIMEFRAME", "4h")
ENTRY_TIMEFRAME = os.getenv("ENTRY_TIMEFRAME", "1h")
KLINE_LIMIT = env_int("KLINE_LIMIT", 300)
SCAN_SLEEP_SECONDS = env_int("SCAN_SLEEP_SECONDS", 900)
SCAN_WAIT_HEARTBEAT_SECONDS = env_int("SCAN_WAIT_HEARTBEAT_SECONDS", 60)
REQUEST_THROTTLE_SECONDS = env_float("REQUEST_THROTTLE_SECONDS", 0.08)
BINANCE_PUBLIC_WEIGHT_LIMIT_PER_MINUTE = env_float(
    "BINANCE_PUBLIC_WEIGHT_LIMIT_PER_MINUTE",
    1800
)
BINANCE_PUBLIC_RATE_WINDOW_SECONDS = env_float(
    "BINANCE_PUBLIC_RATE_WINDOW_SECONDS",
    60
)
PUBLIC_REST_BACKOFF_BUFFER_SECONDS = env_float(
    "PUBLIC_REST_BACKOFF_BUFFER_SECONDS",
    60
)
PUBLIC_REST_DEFAULT_BACKOFF_SECONDS = env_float(
    "PUBLIC_REST_DEFAULT_BACKOFF_SECONDS",
    300
)
PUBLIC_REST_LOG_COOLDOWN_SECONDS = env_float(
    "PUBLIC_REST_LOG_COOLDOWN_SECONDS",
    30
)
KLINE_REQUEST_WEIGHT = env_float("KLINE_REQUEST_WEIGHT", 2)
KLINE_CACHE_SECONDS = env_float("KLINE_CACHE_SECONDS", 45)
KLINE_CACHE_MAX_ITEMS = env_int("KLINE_CACHE_MAX_ITEMS", 2400)
KLINE_CACHE_CANDLE_AWARE_ENABLED = env_bool(
    "KLINE_CACHE_CANDLE_AWARE_ENABLED",
    "True"
)
KLINE_CACHE_CLOSE_GRACE_SECONDS = env_float(
    "KLINE_CACHE_CLOSE_GRACE_SECONDS",
    2
)
SIGNAL_ANALYSIS_CACHE_ENABLED = env_bool(
    "SIGNAL_ANALYSIS_CACHE_ENABLED",
    "True"
)
SIGNAL_ANALYSIS_CACHE_MAX_ITEMS = env_int(
    "SIGNAL_ANALYSIS_CACHE_MAX_ITEMS",
    1200
)
PRIVATE_ACCOUNT_CACHE_SECONDS = env_float(
    "PRIVATE_ACCOUNT_CACHE_SECONDS",
    5
)
PRIVATE_POSITION_CACHE_SECONDS = env_float(
    "PRIVATE_POSITION_CACHE_SECONDS",
    3
)
PRIVATE_REST_STALE_CACHE_SECONDS = env_float(
    "PRIVATE_REST_STALE_CACHE_SECONDS",
    60
)
PRIVATE_REST_BACKOFF_BUFFER_SECONDS = env_float(
    "PRIVATE_REST_BACKOFF_BUFFER_SECONDS",
    60
)
PRIVATE_REST_DEFAULT_BACKOFF_SECONDS = env_float(
    "PRIVATE_REST_DEFAULT_BACKOFF_SECONDS",
    300
)
PRIVATE_REST_LOG_COOLDOWN_SECONDS = env_float(
    "PRIVATE_REST_LOG_COOLDOWN_SECONDS",
    30
)
FUTURES_CONTEXT_REQUEST_WEIGHT = env_float(
    "FUTURES_CONTEXT_REQUEST_WEIGHT",
    1
)
MAX_SCAN_SYMBOLS = env_int("MAX_SCAN_SYMBOLS", 0)
ENTRY_PRICE_RETRIES = env_int("ENTRY_PRICE_RETRIES", 8)
ENTRY_PRICE_RETRY_DELAY_SECONDS = env_float(
    "ENTRY_PRICE_RETRY_DELAY_SECONDS",
    0.25
)
EXECUTION_RECONCILIATION_ENABLED = env_bool(
    "EXECUTION_RECONCILIATION_ENABLED",
    "True"
)
EXECUTION_VERIFY_ATTEMPTS = env_int("EXECUTION_VERIFY_ATTEMPTS", 4)
EXECUTION_VERIFY_DELAY_SECONDS = env_float(
    "EXECUTION_VERIFY_DELAY_SECONDS",
    0.25
)
PENDING_EXECUTION_RECONCILE_SECONDS = env_float(
    "PENDING_EXECUTION_RECONCILE_SECONDS",
    5,
)
PENDING_EXECUTION_ABSENCE_GRACE_SECONDS = env_float(
    "PENDING_EXECUTION_ABSENCE_GRACE_SECONDS",
    60,
)
PENDING_EXECUTION_ABSENCE_CONFIRMATIONS = env_int(
    "PENDING_EXECUTION_ABSENCE_CONFIRMATIONS",
    3,
)
PENDING_EXECUTION_ORDER_HISTORY_LIMIT = env_int(
    "PENDING_EXECUTION_ORDER_HISTORY_LIMIT",
    1000,
)
EXECUTION_RESIDUAL_RETRY_ATTEMPTS = env_int(
    "EXECUTION_RESIDUAL_RETRY_ATTEMPTS",
    1
)
EXECUTION_TELEMETRY_ENABLED = env_bool(
    "EXECUTION_TELEMETRY_ENABLED",
    "True"
)
EXECUTION_TELEMETRY_PATH = os.getenv(
    "EXECUTION_TELEMETRY_PATH",
    "data/execution_telemetry_v7.csv"
)
EXECUTION_TELEMETRY_QUEUE_SIZE = env_int(
    "EXECUTION_TELEMETRY_QUEUE_SIZE",
    2000,
)
SMART_EXECUTION_ENABLED = env_bool("SMART_EXECUTION_ENABLED", "True")
SMART_EXECUTION_TIME_IN_FORCE = os.getenv(
    "SMART_EXECUTION_TIME_IN_FORCE",
    "IOC"
).strip().upper()
SMART_EXECUTION_MAX_CROSS_BPS = env_float(
    "SMART_EXECUTION_MAX_CROSS_BPS",
    2.0
)
SMART_EXECUTION_BOOK_TICKER_WEIGHT = env_float(
    "SMART_EXECUTION_BOOK_TICKER_WEIGHT",
    2
)
SMART_EXECUTION_MARKET_FALLBACK_ENABLED = env_bool(
    "SMART_EXECUTION_MARKET_FALLBACK_ENABLED",
    "True"
)
SMART_EXECUTION_CONTEXTS = {
    item.strip().upper()
    for item in os.getenv(
        "SMART_EXECUTION_CONTEXTS",
        "ENTRY,DCA"
    ).split(",")
    if item.strip()
}
STATE_UPSERT_RETRY_ATTEMPTS = env_int("STATE_UPSERT_RETRY_ATTEMPTS", 3)
STATE_UPSERT_RETRY_DELAY_SECONDS = env_float(
    "STATE_UPSERT_RETRY_DELAY_SECONDS",
    0.25
)
REQUIRE_STATE_FOR_OPEN_POSITIONS = env_bool(
    "REQUIRE_STATE_FOR_OPEN_POSITIONS",
    "True",
)
PROTECTION_FAILURE_CLOSE_ENABLED = env_bool(
    "PROTECTION_FAILURE_CLOSE_ENABLED",
    "True"
)
UNTRACKED_POSITION_FAIL_CLOSE_ENABLED = env_bool(
    "UNTRACKED_POSITION_FAIL_CLOSE_ENABLED",
    "False",
)
REQUIRE_ONE_WAY_POSITION_MODE = env_bool(
    "REQUIRE_ONE_WAY_POSITION_MODE",
    "True",
)
PROTECTION_ORDER_DELAY_SECONDS = env_float(
    "PROTECTION_ORDER_DELAY_SECONDS",
    0.15
)
TP_ORDER_RETRY_ATTEMPTS = env_int("TP_ORDER_RETRY_ATTEMPTS", 2)
TP_ORDER_RETRY_DELAY_SECONDS = env_float("TP_ORDER_RETRY_DELAY_SECONDS", 1)
TP_FAILURE_FALLBACK_ROI_ENABLED = env_bool(
    "TP_FAILURE_FALLBACK_ROI_ENABLED",
    "True"
)
POST_TRADE_SLEEP_SECONDS = env_float("POST_TRADE_SLEEP_SECONDS", 0.25)

TARGET_MARGIN_BALANCE_STOP_ENABLED = env_bool(
    "TARGET_MARGIN_BALANCE_STOP_ENABLED",
    "False"
)
TARGET_MARGIN_BALANCE = env_float("TARGET_MARGIN_BALANCE", 0)
TARGET_MARGIN_BALANCE_CHECK_SECONDS = env_float(
    "TARGET_MARGIN_BALANCE_CHECK_SECONDS",
    10
)
TARGET_MARGIN_BALANCE_MIN_CHECK_SECONDS = env_float(
    "TARGET_MARGIN_BALANCE_MIN_CHECK_SECONDS",
    5
)
TARGET_MARGIN_CLOSE_RETRIES = env_int("TARGET_MARGIN_CLOSE_RETRIES", 2)
TARGET_MARGIN_CLOSE_VERIFY_SECONDS = env_float(
    "TARGET_MARGIN_CLOSE_VERIFY_SECONDS",
    2
)
TARGET_MARGIN_CLOSE_RETRY_SECONDS = env_float(
    "TARGET_MARGIN_CLOSE_RETRY_SECONDS",
    2
)
TARGET_MARGIN_FORCE_EXIT_ENABLED = env_bool(
    "TARGET_MARGIN_FORCE_EXIT_ENABLED",
    "True"
)
TARGET_MARGIN_EXIT_DELAY_SECONDS = env_float(
    "TARGET_MARGIN_EXIT_DELAY_SECONDS",
    3
)

SIGNAL_RANKING_ENABLED = env_bool("SIGNAL_RANKING_ENABLED", "True")
SIGNAL_RANKING_MAX_CANDIDATES = env_int("SIGNAL_RANKING_MAX_CANDIDATES", 0)
SIGNAL_RANKING_QUALITY_WEIGHT = env_float("SIGNAL_RANKING_QUALITY_WEIGHT", 1.5)
SIGNAL_RANKING_FLOW_WEIGHT = env_float("SIGNAL_RANKING_FLOW_WEIGHT", 1.2)
SIGNAL_RANKING_SMC_WEIGHT = env_float("SIGNAL_RANKING_SMC_WEIGHT", 1.0)
SIGNAL_RANKING_REGIME_WEIGHT = env_float("SIGNAL_RANKING_REGIME_WEIGHT", 1.0)
# Promotes order_flow_shadow's footprint/impact/CVD analytics into a bounded
# ranking contribution, reusing its existing buy/sell_shadow_score fields the
# same way MARKET_FLOW_RANK_WEIGHT already uses MarketFlowMonitor's scores.
# Ships disabled: this is separate from and does not alter the module's
# existing shadow-only telemetry snapshot (attach_candidate_shadow_order_flow
# / candidate["shadow_order_flow"]), which remains observation-only.
SIGNAL_RANKING_ORDERFLOW_ENABLED = env_bool(
    "SIGNAL_RANKING_ORDERFLOW_ENABLED",
    "False"
)
SIGNAL_RANKING_ORDERFLOW_WEIGHT = env_float(
    "SIGNAL_RANKING_ORDERFLOW_WEIGHT",
    1.0
)
TREND_TIMING_RESCUE_RANK_PENALTY = env_float(
    "TREND_TIMING_RESCUE_RANK_PENALTY",
    2.5
)
CONTINUATION_PULLBACK_RANK_PENALTY = env_float(
    "CONTINUATION_PULLBACK_RANK_PENALTY",
    1.5
)
FUTURES_CONTEXT_PRIORITY_PULLBACK_BONUS = env_float(
    "FUTURES_CONTEXT_PRIORITY_PULLBACK_BONUS",
    8
)
FUTURES_CONTEXT_PRIORITY_RESCUE_BONUS = env_float(
    "FUTURES_CONTEXT_PRIORITY_RESCUE_BONUS",
    5
)
FUTURES_CONTEXT_PRIORITY_REVERSAL_BONUS = env_float(
    "FUTURES_CONTEXT_PRIORITY_REVERSAL_BONUS",
    6
)
FUTURES_CONTEXT_PRIORITY_SIGNAL_BONUS = env_float(
    "FUTURES_CONTEXT_PRIORITY_SIGNAL_BONUS",
    3
)

SIGNAL_JOURNAL_ENABLED = env_bool("SIGNAL_JOURNAL_ENABLED", "True")
SIGNAL_JOURNAL_PATH = os.getenv("SIGNAL_JOURNAL_PATH", "data/signal_journal.csv")
SIGNAL_OUTCOME_TRACKING_ENABLED = env_bool(
    "SIGNAL_OUTCOME_TRACKING_ENABLED",
    "True"
)
SIGNAL_OUTCOME_PATH = os.getenv(
    "SIGNAL_OUTCOME_PATH",
    "data/signal_outcomes_v7.csv"
)
SIGNAL_OUTCOME_STATE_PATH = os.getenv(
    "SIGNAL_OUTCOME_STATE_PATH",
    "data/signal_outcomes_pending_v7.json"
)
SIGNAL_OUTCOME_HORIZON_HOURS = env_float_list(
    "SIGNAL_OUTCOME_HORIZON_HOURS",
    [1, 4, 12, 24]
)
SIGNAL_CALIBRATION_ENABLED = env_bool(
    "SIGNAL_CALIBRATION_ENABLED",
    "True"
)
SIGNAL_CALIBRATION_PATH = os.getenv(
    "SIGNAL_CALIBRATION_PATH",
    "data/signal_calibration_v7.json"
)
SIGNAL_CALIBRATION_MIN_SAMPLES = env_int(
    "SIGNAL_CALIBRATION_MIN_SAMPLES",
    30
)
SIGNAL_CALIBRATION_BUCKET_WIDTH = env_float(
    "SIGNAL_CALIBRATION_BUCKET_WIDTH",
    5
)
SIGNAL_CALIBRATION_PRIOR_STRENGTH = env_float(
    "SIGNAL_CALIBRATION_PRIOR_STRENGTH",
    10
)
SIGNAL_CALIBRATION_SUCCESS_RETURN_PCT = env_float(
    "SIGNAL_CALIBRATION_SUCCESS_RETURN_PCT",
    0.1
)
SIGNAL_CALIBRATION_RANK_WEIGHT = env_float(
    "SIGNAL_CALIBRATION_RANK_WEIGHT",
    8
)
FUTURES_CONTEXT_ENABLED = env_bool("FUTURES_CONTEXT_ENABLED", "True")
FUTURES_CONTEXT_MIN_CONFIDENCE = env_float("FUTURES_CONTEXT_MIN_CONFIDENCE", 60)
FUTURES_CONTEXT_PERIOD = os.getenv("FUTURES_CONTEXT_PERIOD", "4h")
FUTURES_CONTEXT_LIMIT = env_int("FUTURES_CONTEXT_LIMIT", 8)
FUTURES_CONTEXT_CACHE_SECONDS = env_int("FUTURES_CONTEXT_CACHE_SECONDS", 900)
FUTURES_CONTEXT_MAX_SYMBOLS_PER_SCAN = env_int(
    "FUTURES_CONTEXT_MAX_SYMBOLS_PER_SCAN",
    12
)
FUTURES_CONTEXT_OI_MIN_CHANGE_PCT = env_float(
    "FUTURES_CONTEXT_OI_MIN_CHANGE_PCT",
    1.0
)
FUTURES_CONTEXT_PRICE_MIN_CHANGE_PCT = env_float(
    "FUTURES_CONTEXT_PRICE_MIN_CHANGE_PCT",
    0.5
)
FUTURES_CONTEXT_TAKER_EMA_ALPHA = env_float(
    "FUTURES_CONTEXT_TAKER_EMA_ALPHA",
    0.35
)
FUTURES_CONTEXT_TAKER_BUY_MIN = env_float("FUTURES_CONTEXT_TAKER_BUY_MIN", 1.05)
FUTURES_CONTEXT_TAKER_SELL_MAX = env_float("FUTURES_CONTEXT_TAKER_SELL_MAX", 0.95)
FUTURES_CONTEXT_CROWD_LONG_MAX = env_float(
    "FUTURES_CONTEXT_CROWD_LONG_MAX",
    2.2
)
FUTURES_CONTEXT_CROWD_SHORT_MIN = env_float(
    "FUTURES_CONTEXT_CROWD_SHORT_MIN",
    0.45
)
FUTURES_CONTEXT_FUNDING_ABS_MAX = env_float(
    "FUTURES_CONTEXT_FUNDING_ABS_MAX",
    0.001
)
FUTURES_CONTEXT_SCORE_WEIGHT = env_float("FUTURES_CONTEXT_SCORE_WEIGHT", 1.15)
FUTURES_CONTEXT_BLOCK_CONFLICT_ENABLED = env_bool(
    "FUTURES_CONTEXT_BLOCK_CONFLICT_ENABLED",
    "True"
)
FUTURES_CONTEXT_MIN_SIGNAL_SCORE = env_float(
    "FUTURES_CONTEXT_MIN_SIGNAL_SCORE",
    -0.5
)

MARKET_FLOW_ENABLED = env_bool("MARKET_FLOW_ENABLED", "True")
MARKET_FLOW_STREAMS_PER_SOCKET = env_int("MARKET_FLOW_STREAMS_PER_SOCKET", 100)
MARKET_FLOW_BOOK_STREAMS_PER_SOCKET = env_int(
    "MARKET_FLOW_BOOK_STREAMS_PER_SOCKET",
    80
)
MARKET_FLOW_STALE_SECONDS = env_float("MARKET_FLOW_STALE_SECONDS", 45)
MARKET_FLOW_WATCHDOG_INTERVAL_SECONDS = env_float(
    "MARKET_FLOW_WATCHDOG_INTERVAL_SECONDS",
    15
)
MARKET_FLOW_RESTART_COOLDOWN_SECONDS = env_float(
    "MARKET_FLOW_RESTART_COOLDOWN_SECONDS",
    30
)
MARKET_FLOW_MAX_WINDOW_SECONDS = env_int("MARKET_FLOW_MAX_WINDOW_SECONDS", 900)
MARKET_FLOW_MIN_NOTIONAL_USDT = env_float(
    "MARKET_FLOW_MIN_NOTIONAL_USDT",
    25000
)
MARKET_FLOW_DEPTH_EMA_ALPHA = env_float("MARKET_FLOW_DEPTH_EMA_ALPHA", 0.15)
MARKET_FLOW_MICROPRICE_SCALE_BPS = env_float(
    "MARKET_FLOW_MICROPRICE_SCALE_BPS",
    2
)
MARKET_FLOW_MAX_SCORE = env_float("MARKET_FLOW_MAX_SCORE", 5)
MARKET_FLOW_RANK_WEIGHT = env_float("MARKET_FLOW_RANK_WEIGHT", 1)
MARKET_FLOW_COMPONENT_CONFLICT_THRESHOLD = env_float(
    "MARKET_FLOW_COMPONENT_CONFLICT_THRESHOLD",
    0.12
)
MARKET_FLOW_HARD_VETO_ENABLED = env_bool(
    "MARKET_FLOW_HARD_VETO_ENABLED",
    "False"
)
MARKET_FLOW_HARD_VETO_SCORE = env_float("MARKET_FLOW_HARD_VETO_SCORE", -4)
MARKET_FLOW_HARD_VETO_MIN_CONFLICTS = env_int(
    "MARKET_FLOW_HARD_VETO_MIN_CONFLICTS",
    3
)

# Observation-only order flow. These values must never be consumed by signal
# ranking, filtering, position sizing, or execution decisions.
ORDER_FLOW_SHADOW_ENABLED = env_bool("ORDER_FLOW_SHADOW_ENABLED", "True")
ORDER_FLOW_SHADOW_MAX_SYMBOLS = env_int("ORDER_FLOW_SHADOW_MAX_SYMBOLS", 12)
ORDER_FLOW_SHADOW_SYMBOLS = tuple(
    item.strip().upper()
    for item in os.getenv("ORDER_FLOW_SHADOW_SYMBOLS", "").split(",")
    if item.strip()
)
ORDER_FLOW_SHADOW_DEPTH_STREAMS_PER_SOCKET = env_int(
    "ORDER_FLOW_SHADOW_DEPTH_STREAMS_PER_SOCKET",
    12
)
ORDER_FLOW_SHADOW_DEPTH_UPDATE_MS = env_int(
    "ORDER_FLOW_SHADOW_DEPTH_UPDATE_MS",
    100
)
ORDER_FLOW_SHADOW_DEPTH_SNAPSHOT_LIMIT = env_int(
    "ORDER_FLOW_SHADOW_DEPTH_SNAPSHOT_LIMIT",
    1000
)
ORDER_FLOW_SHADOW_CORE_WEIGHT_RESERVE = env_float(
    "ORDER_FLOW_SHADOW_CORE_WEIGHT_RESERVE",
    500
)
ORDER_FLOW_SHADOW_SNAPSHOT_RETRY_SECONDS = env_float(
    "ORDER_FLOW_SHADOW_SNAPSHOT_RETRY_SECONDS",
    10
)
ORDER_FLOW_SHADOW_QUEUE_SIZE = env_int("ORDER_FLOW_SHADOW_QUEUE_SIZE", 20000)
ORDER_FLOW_SHADOW_MAX_TRADES_PER_SYMBOL = env_int(
    "ORDER_FLOW_SHADOW_MAX_TRADES_PER_SYMBOL",
    50000
)
ORDER_FLOW_SHADOW_WINDOW_SECONDS = env_int("ORDER_FLOW_SHADOW_WINDOW_SECONDS", 300)
ORDER_FLOW_SHADOW_BUCKET_BPS = env_float("ORDER_FLOW_SHADOW_BUCKET_BPS", 1.0)
ORDER_FLOW_SHADOW_MIN_BUCKET_NOTIONAL = env_float(
    "ORDER_FLOW_SHADOW_MIN_BUCKET_NOTIONAL",
    5000
)
ORDER_FLOW_SHADOW_IMBALANCE_RATIO = env_float(
    "ORDER_FLOW_SHADOW_IMBALANCE_RATIO",
    3.0
)
ORDER_FLOW_SHADOW_STALE_SECONDS = env_float("ORDER_FLOW_SHADOW_STALE_SECONDS", 15)
ORDER_FLOW_SHADOW_IMPACT_NOTIONAL_USDT = env_float(
    "ORDER_FLOW_SHADOW_IMPACT_NOTIONAL_USDT",
    10000
)
ORDER_FLOW_SHADOW_TELEMETRY_ENABLED = env_bool(
    "ORDER_FLOW_SHADOW_TELEMETRY_ENABLED",
    "True"
)
ORDER_FLOW_SHADOW_TELEMETRY_PATH = os.getenv(
    "ORDER_FLOW_SHADOW_TELEMETRY_PATH",
    "data/order_flow_shadow_v7.csv"
)
ORDER_FLOW_SHADOW_TELEMETRY_MIN_INTERVAL_SECONDS = env_float(
    "ORDER_FLOW_SHADOW_TELEMETRY_MIN_INTERVAL_SECONDS",
    30
)

# Observation-only volume profile (POC/VAH/VAL), logged alongside
# detect_market_structure's read for comparison. Not imported by strategy.py
# and does not affect signal ranking, filtering, sizing, or execution -
# same shadow-mode principle as ORDER_FLOW_SHADOW above.
VOLUME_PROFILE_TELEMETRY_ENABLED = env_bool(
    "VOLUME_PROFILE_TELEMETRY_ENABLED",
    "True"
)
VOLUME_PROFILE_LOOKBACK = env_int("VOLUME_PROFILE_LOOKBACK", 120)
VOLUME_PROFILE_BINS = env_int("VOLUME_PROFILE_BINS", 24)
VOLUME_PROFILE_VALUE_AREA_PCT = env_float("VOLUME_PROFILE_VALUE_AREA_PCT", 0.70)
VOLUME_PROFILE_TELEMETRY_PATH = os.getenv(
    "VOLUME_PROFILE_TELEMETRY_PATH",
    "data/volume_profile_v7.csv"
)
VOLUME_PROFILE_TELEMETRY_MIN_INTERVAL_SECONDS = env_float(
    "VOLUME_PROFILE_TELEMETRY_MIN_INTERVAL_SECONDS",
    240
)

MARKET_BREADTH_ENABLED = env_bool("MARKET_BREADTH_ENABLED", "True")
MARKET_BREADTH_MIN_SAMPLES = env_int("MARKET_BREADTH_MIN_SAMPLES", 20)
MARKET_BREADTH_MAX_SCORE = env_float("MARKET_BREADTH_MAX_SCORE", 3)
MARKET_BREADTH_RANK_WEIGHT = env_float("MARKET_BREADTH_RANK_WEIGHT", 1)

REGIME_TRANSITION_ENABLED = env_bool("REGIME_TRANSITION_ENABLED", "True")
REGIME_TRANSITION_RECENT_CANDLES = env_int(
    "REGIME_TRANSITION_RECENT_CANDLES",
    6
)
REGIME_TRANSITION_BASELINE_CANDLES = env_int(
    "REGIME_TRANSITION_BASELINE_CANDLES",
    30
)
REGIME_TRANSITION_Z_THRESHOLD = env_float("REGIME_TRANSITION_Z_THRESHOLD", 1.5)
REGIME_TRANSITION_VOLATILITY_RATIO = env_float(
    "REGIME_TRANSITION_VOLATILITY_RATIO",
    1.6
)
REGIME_TRANSITION_MAX_SCORE = env_float("REGIME_TRANSITION_MAX_SCORE", 2)
REGIME_TRANSITION_RANK_WEIGHT = env_float("REGIME_TRANSITION_RANK_WEIGHT", 1)
SIGNAL_RANKING_UNCAPPED_INDEX_MAX = env_float(
    "SIGNAL_RANKING_UNCAPPED_INDEX_MAX",
    140
)

NEWS_FILTER_ENABLED = env_bool("NEWS_FILTER_ENABLED", "False")
NEWS_PROVIDER = os.getenv("NEWS_PROVIDER", "cryptopanic")
NEWS_API_KEY = os.getenv("NEWS_API_KEY", "")
NEWS_CACHE_PATH = os.getenv("NEWS_CACHE_PATH", "data/news_cache.json")
NEWS_CACHE_SECONDS = env_int("NEWS_CACHE_SECONDS", 1800)
NEWS_STALE_CACHE_SECONDS = env_int("NEWS_STALE_CACHE_SECONDS", 86400)
NEWS_RATE_LIMIT_BACKOFF_SECONDS = env_int("NEWS_RATE_LIMIT_BACKOFF_SECONDS", 3600)
NEWS_TIMEOUT_SECONDS = env_float("NEWS_TIMEOUT_SECONDS", 5)
NEWS_MAX_ITEMS = env_int("NEWS_MAX_ITEMS", 8)
NEWS_MIN_HEADLINES = env_int("NEWS_MIN_HEADLINES", 1)
NEWS_BULLISH_SCORE = env_float("NEWS_BULLISH_SCORE", 0.35)
NEWS_BEARISH_SCORE = env_float("NEWS_BEARISH_SCORE", -0.35)
NEWS_BUY_BLOCK_SCORE = env_float("NEWS_BUY_BLOCK_SCORE", -0.65)
NEWS_SELL_BLOCK_SCORE = env_float("NEWS_SELL_BLOCK_SCORE", 0.65)
NEWS_CONFIDENCE_BOOST = env_float("NEWS_CONFIDENCE_BOOST", 3)
NEWS_CONFIDENCE_PENALTY = env_float("NEWS_CONFIDENCE_PENALTY", 5)
NEWS_BLOCK_HIGH_IMPACT = env_bool("NEWS_BLOCK_HIGH_IMPACT", "True")

LLM_FILTER_ENABLED = env_bool("LLM_FILTER_ENABLED", "False")
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "openai").strip().lower()
LLM_API_KEY = os.getenv("LLM_API_KEY", "")
LLM_MODEL = os.getenv("LLM_MODEL", "")
LLM_BASE_URL = os.getenv(
    "LLM_BASE_URL",
    "https://api.openai.com/v1/chat/completions"
)
LLM_TIMEOUT_SECONDS = env_float("LLM_TIMEOUT_SECONDS", 8)
LLM_MAX_RETRIES = env_int("LLM_MAX_RETRIES", 1)
LLM_CONFIDENCE_BOOST = env_float("LLM_CONFIDENCE_BOOST", 3)
LLM_CONFIDENCE_PENALTY = env_float("LLM_CONFIDENCE_PENALTY", 5)
LLM_BLOCK_HIGH_RISK = env_bool("LLM_BLOCK_HIGH_RISK", "True")
LLM_FAIL_OPEN = env_bool("LLM_FAIL_OPEN", "True")
LLM_CACHE_SECONDS = env_int("LLM_CACHE_SECONDS", 900)
LLM_STALE_CACHE_SECONDS = env_int("LLM_STALE_CACHE_SECONDS", 86400)
LLM_RATE_LIMIT_BACKOFF_SECONDS = env_int("LLM_RATE_LIMIT_BACKOFF_SECONDS", 3600)
LLM_MAX_REQUESTS_PER_SCAN = env_int("LLM_MAX_REQUESTS_PER_SCAN", 0)
LLM_CACHE_PATH = os.getenv("LLM_CACHE_PATH", "data/llm_cache.json")
LLM_MAX_PROMPT_CHARS = env_int("LLM_MAX_PROMPT_CHARS", 6000)
LLM_BATCH_ENABLED = env_bool("LLM_BATCH_ENABLED", "True")
LLM_BATCH_MAX_CANDIDATES = env_int("LLM_BATCH_MAX_CANDIDATES", 20)
LLM_BATCH_MAX_PROMPT_CHARS = env_int("LLM_BATCH_MAX_PROMPT_CHARS", 30000)
LLM_SYMBOL_SIDE_CACHE_SECONDS = env_int(
    "LLM_SYMBOL_SIDE_CACHE_SECONDS",
    3600
)
LLM_CONFIDENCE_BUCKET_SIZE = env_float("LLM_CONFIDENCE_BUCKET_SIZE", 5)
LLM_MIN_REQUEST_INTERVAL_SECONDS = env_float(
    "LLM_MIN_REQUEST_INTERVAL_SECONDS",
    5
)
LLM_SHARED_RATE_LIMIT_PATH = os.getenv(
    "LLM_SHARED_RATE_LIMIT_PATH",
    "~/.binance_ai_bots/llm_rate_limit.json"
)
LLM_SHARED_LOCK_TIMEOUT_SECONDS = env_float(
    "LLM_SHARED_LOCK_TIMEOUT_SECONDS",
    1
)
LLM_QUOTA_BACKOFF_SECONDS = env_int("LLM_QUOTA_BACKOFF_SECONDS", 21600)
LLM_RATE_LIMIT_SAFETY_SECONDS = env_float(
    "LLM_RATE_LIMIT_SAFETY_SECONDS",
    1
)
LLM_MAX_BACKOFF_SECONDS = env_int("LLM_MAX_BACKOFF_SECONDS", 43200)
LLM_RETRY_BASE_SECONDS = env_float("LLM_RETRY_BASE_SECONDS", 1)
LLM_RETRY_MAX_SECONDS = env_float("LLM_RETRY_MAX_SECONDS", 8)

TELEGRAM_ENABLED = env_bool("TELEGRAM_ENABLED", "False")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")
TELEGRAM_TIMEOUT_SECONDS = env_float("TELEGRAM_TIMEOUT_SECONDS", 5)
TELEGRAM_MESSAGE_PREFIX = os.getenv("TELEGRAM_MESSAGE_PREFIX", "Binance Bot")

SMC_ENABLED = env_bool("SMC_ENABLED", "True")
SMC_SWEEP_ENABLED = env_bool("SMC_SWEEP_ENABLED", "True")
SMC_OB_ENABLED = env_bool("SMC_OB_ENABLED", "True")
SMC_FVG_ENABLED = env_bool("SMC_FVG_ENABLED", "True")
SMC_SWEEP_LOOKBACK = env_int("SMC_SWEEP_LOOKBACK", 24)
SMC_SWEEP_MAX_AGE = env_int("SMC_SWEEP_MAX_AGE", 5)
SMC_OB_LOOKBACK = env_int("SMC_OB_LOOKBACK", 120)
SMC_OB_DISPLACEMENT_ATR = env_float("SMC_OB_DISPLACEMENT_ATR", 0.8)
SMC_OB_MAX_ZONE_PCT = env_float("SMC_OB_MAX_ZONE_PCT", 4.0)
SMC_FVG_LOOKBACK = env_int("SMC_FVG_LOOKBACK", 120)
SMC_FVG_MIN_GAP_ATR = env_float("SMC_FVG_MIN_GAP_ATR", 0.12)
SMC_TP_PATH_BLOCK_PENALTY = env_float("SMC_TP_PATH_BLOCK_PENALTY", 1.5)

LIVE_ENTRY_CONFIRMATION_ENABLED = env_bool("LIVE_ENTRY_CONFIRMATION_ENABLED", "True")
LIVE_ENTRY_FAST_TIMEFRAME = os.getenv("LIVE_ENTRY_FAST_TIMEFRAME", "5m")
LIVE_ENTRY_SLOW_TIMEFRAME = os.getenv("LIVE_ENTRY_SLOW_TIMEFRAME", "15m")
LIVE_ENTRY_KLINE_LIMIT = env_int("LIVE_ENTRY_KLINE_LIMIT", 80)
LIVE_ENTRY_REQUIRE_DATA = env_bool("LIVE_ENTRY_REQUIRE_DATA", "False")
LIVE_ENTRY_STRUCTURE_LOOKBACK = env_int("LIVE_ENTRY_STRUCTURE_LOOKBACK", 12)
LIVE_ENTRY_STRUCTURE_BUFFER_ATR = env_float("LIVE_ENTRY_STRUCTURE_BUFFER_ATR", 0.08)
LIVE_ENTRY_MIN_REVERSAL_BODY_ATR = env_float(
    "LIVE_ENTRY_MIN_REVERSAL_BODY_ATR",
    0.35
)
LIVE_ENTRY_REVERSAL_CLOSE_POSITION = env_float(
    "LIVE_ENTRY_REVERSAL_CLOSE_POSITION",
    0.30
)
MAX_LIVE_ENTRY_RETRACE_ATR = env_float("MAX_LIVE_ENTRY_RETRACE_ATR", 0.20)
MAX_LIVE_ENTRY_CHASE_ATR = env_float("MAX_LIVE_ENTRY_CHASE_ATR", 0.50)
LIVE_ENTRY_EMA_TOLERANCE_PCT = env_float("LIVE_ENTRY_EMA_TOLERANCE_PCT", 0.08)
MAX_LIVE_ENTRY_CLOSE_POSITION = env_float("MAX_LIVE_ENTRY_CLOSE_POSITION", 0.88)
LIVE_ENTRY_REQUIRE_DIRECTION_SUPPORT = env_bool(
    "LIVE_ENTRY_REQUIRE_DIRECTION_SUPPORT",
    "True"
)
LIVE_ENTRY_REQUIRE_BOTH_TIMEFRAMES = env_bool(
    "LIVE_ENTRY_REQUIRE_BOTH_TIMEFRAMES",
    "False"
)
LIVE_ENTRY_MIN_SUPPORT_SCORE = env_float("LIVE_ENTRY_MIN_SUPPORT_SCORE", 1.0)
LIVE_ENTRY_DUAL_OPPOSITION_BLOCK_SCORE = env_float(
    "LIVE_ENTRY_DUAL_OPPOSITION_BLOCK_SCORE",
    -0.75
)
LIVE_ENTRY_CHASE_RELAX_ENABLED = env_bool(
    "LIVE_ENTRY_CHASE_RELAX_ENABLED",
    "False"
)
LIVE_ENTRY_CHASE_RELAX_MIN_CONFIDENCE = env_float(
    "LIVE_ENTRY_CHASE_RELAX_MIN_CONFIDENCE",
    95.0
)
LIVE_ENTRY_CHASE_RELAXED_MAX_ATR = env_float(
    "LIVE_ENTRY_CHASE_RELAXED_MAX_ATR",
    1.2
)

EARLY_FLOW_EXIT_ENABLED = env_bool("EARLY_FLOW_EXIT_ENABLED", "False")
EARLY_FLOW_EXIT_TREND_ENABLED = env_bool(
    "EARLY_FLOW_EXIT_TREND_ENABLED",
    "True"
)
EARLY_FLOW_EXIT_REVERSAL_ENABLED = env_bool(
    "EARLY_FLOW_EXIT_REVERSAL_ENABLED",
    "True"
)
EARLY_FLOW_EXIT_MINUTES = env_float("EARLY_FLOW_EXIT_MINUTES", 15)
EARLY_FLOW_EXIT_POST_DCA_GRACE_MINUTES = env_float(
    "EARLY_FLOW_EXIT_POST_DCA_GRACE_MINUTES",
    EARLY_FLOW_EXIT_MINUTES
)
EARLY_FLOW_EXIT_MAX_ROI = env_float("EARLY_FLOW_EXIT_MAX_ROI", -1)
EARLY_FLOW_EXIT_TREND_MAX_ROI = env_float(
    "EARLY_FLOW_EXIT_TREND_MAX_ROI",
    EARLY_FLOW_EXIT_MAX_ROI
)
EARLY_FLOW_EXIT_REVERSAL_MAX_ROI = env_float(
    "EARLY_FLOW_EXIT_REVERSAL_MAX_ROI",
    EARLY_FLOW_EXIT_MAX_ROI
)
EARLY_FLOW_EXIT_CHECK_SECONDS = env_float(
    "EARLY_FLOW_EXIT_CHECK_SECONDS",
    60
)
EARLY_FLOW_EXIT_REFERENCE_BUFFER_PCT = env_float(
    "EARLY_FLOW_EXIT_REFERENCE_BUFFER_PCT",
    0.15
)
EARLY_FLOW_EXIT_EMA_TOLERANCE_PCT = env_float(
    "EARLY_FLOW_EXIT_EMA_TOLERANCE_PCT",
    LIVE_ENTRY_EMA_TOLERANCE_PCT
)
EARLY_FLOW_EXIT_REQUIRE_DATA = env_bool(
    "EARLY_FLOW_EXIT_REQUIRE_DATA",
    "True"
)

TIME_EXIT_ENABLED = env_bool("TIME_EXIT_ENABLED", "False")
TIME_EXIT_TREND_ENABLED = env_bool("TIME_EXIT_TREND_ENABLED", "True")
TIME_EXIT_REVERSAL_ENABLED = env_bool("TIME_EXIT_REVERSAL_ENABLED", "False")
TIME_EXIT_MINUTES = env_float("TIME_EXIT_MINUTES", 480)
TIME_EXIT_MAX_ROI = env_float("TIME_EXIT_MAX_ROI", 0)
TIME_EXIT_CHECK_SECONDS = env_float("TIME_EXIT_CHECK_SECONDS", 60)
TIME_EXIT_PENDING_RETRY_SECONDS = env_float(
    "TIME_EXIT_PENDING_RETRY_SECONDS",
    60,
)
TIME_EXIT_POST_DCA_GRACE_MINUTES = env_float(
    "TIME_EXIT_POST_DCA_GRACE_MINUTES",
    30,
)
TIME_EXIT_REQUIRE_WEAKNESS = env_bool(
    "TIME_EXIT_REQUIRE_WEAKNESS",
    "True",
)
TIME_EXIT_REQUIRE_DATA = env_bool("TIME_EXIT_REQUIRE_DATA", "True")
TIME_EXIT_MIN_WEAKNESS_SCORE = env_float(
    "TIME_EXIT_MIN_WEAKNESS_SCORE",
    2,
)

LEVERAGE = env_int("LEVERAGE", 5)
MARGIN_TYPE = os.getenv("MARGIN_TYPE", "CROSSED").upper()
MARGIN_PER_TRADE = env_float("MARGIN_PER_TRADE", 5)
RISK_BASED_POSITION_SIZING_ENABLED = env_bool(
    "RISK_BASED_POSITION_SIZING_ENABLED",
    "False",
)
POSITION_RISK_PCT = env_float("POSITION_RISK_PCT", 0.5)
POSITION_RISK_MAX_USDT = env_float("POSITION_RISK_MAX_USDT", 0)
POSITION_RISK_OVERRUN_TOLERANCE_PCT = env_float(
    "POSITION_RISK_OVERRUN_TOLERANCE_PCT",
    2,
)
POSITION_MANAGEMENT_LEGACY_ENABLED = env_bool(
    "POSITION_MANAGEMENT_LEGACY_ENABLED",
    "False",
)

STATIC_TP_ENABLED = env_bool("STATIC_TP_ENABLED", "True")
STATIC_TP_ROI = env_float("STATIC_TP_ROI", env_float("ROI_PERCENT_TP", 6))
ROI_PERCENT_TP = env_float("ROI_PERCENT_TP", STATIC_TP_ROI)
STRUCTURE_TP_MIN_ROI = env_float("STRUCTURE_TP_MIN_ROI", 8)
STRUCTURE_TP_MAX_ROI = env_float("STRUCTURE_TP_MAX_ROI", 120)
STRUCTURE_TP_MIN_SCORE = env_float("STRUCTURE_TP_MIN_SCORE", 2.0)
STRUCTURE_TP_BUFFER_PCT = env_float("STRUCTURE_TP_BUFFER_PCT", 0.15)
STRUCTURE_TP_ATR_BUFFER_MULT = env_float("STRUCTURE_TP_ATR_BUFFER_MULT", 0.25)
STRUCTURE_TP_FALLBACK_ROI = env_float("STRUCTURE_TP_FALLBACK_ROI", ROI_PERCENT_TP)
REVERSAL_TP_MAX_ROI = env_float("REVERSAL_TP_MAX_ROI", 45)
REVERSAL_TP_FALLBACK_ROI = env_float("REVERSAL_TP_FALLBACK_ROI", 35)
MULTI_TP_ENABLED = env_bool("MULTI_TP_ENABLED", "True")
TP1_CLOSE_POSITION_PCT = env_float("TP1_CLOSE_POSITION_PCT", 75)
TP1_MAX_CLOSE_PCT_DEVIATION = env_float(
    "TP1_MAX_CLOSE_PCT_DEVIATION",
    5,
)
TP2_FALLBACK_ROI = env_float("TP2_FALLBACK_ROI", 50)
TP1_RUNNER_STOP_ENABLED = env_bool("TP1_RUNNER_STOP_ENABLED", "True")
TP1_RUNNER_MIN_LOCK_ROI = env_float("TP1_RUNNER_MIN_LOCK_ROI", 5)
TP1_RUNNER_BREAKEVEN_BUFFER_PCT = env_float(
    "TP1_RUNNER_BREAKEVEN_BUFFER_PCT",
    0.12
)
TP1_RUNNER_ATR_BUFFER_MULT = env_float(
    "TP1_RUNNER_ATR_BUFFER_MULT",
    0.50
)
TP1_RUNNER_STRUCTURE_BUFFER_ATR = env_float(
    "TP1_RUNNER_STRUCTURE_BUFFER_ATR",
    0.15
)
TP1_RUNNER_STRUCTURE_LOOKBACK = env_int(
    "TP1_RUNNER_STRUCTURE_LOOKBACK",
    8
)
TP1_RUNNER_MIN_STOP_DISTANCE_ATR = env_float(
    "TP1_RUNNER_MIN_STOP_DISTANCE_ATR",
    0.20
)
TP1_RUNNER_RETRY_SECONDS = env_float("TP1_RUNNER_RETRY_SECONDS", 5)
TP1_HEALTH_CHECK_SECONDS = env_float("TP1_HEALTH_CHECK_SECONDS", 60)
TP1_RUNNER_DISABLE_DCA = env_bool("TP1_RUNNER_DISABLE_DCA", "True")
ENTRY_TP_ROOM_CHECK_ENABLED = env_bool("ENTRY_TP_ROOM_CHECK_ENABLED", "True")
ENTRY_MIN_TP_ROOM_ROI = env_float("ENTRY_MIN_TP_ROOM_ROI", STRUCTURE_TP_MIN_ROI)
ENTRY_TP_ROOM_MIN_LEVEL_SCORE = env_float(
    "ENTRY_TP_ROOM_MIN_LEVEL_SCORE",
    STRUCTURE_TP_MIN_SCORE
)
ENTRY_TP_ROOM_BLOCK_IF_NO_LEVEL = env_bool(
    "ENTRY_TP_ROOM_BLOCK_IF_NO_LEVEL",
    "False"
)

DCA_ENABLED = env_bool("DCA_ENABLED", "False")
DCA_MANAGE_EXISTING_POSITIONS = env_bool("DCA_MANAGE_EXISTING_POSITIONS", "False")
DCA_STATE_PATH = os.getenv("DCA_STATE_PATH", "data/open_trades_v7.json")
DCA_MAX_ORDERS = env_int("DCA_MAX_ORDERS", 2)
DCA_INITIAL_MARGIN_PCT = env_float("DCA_INITIAL_MARGIN_PCT", 50)
DCA_MARGIN_PCTS = env_float_list("DCA_MARGIN_PCTS", [30, 20])
DCA_INITIAL_RISK_PCT = env_float("DCA_INITIAL_RISK_PCT", 70)
DCA_RECOVERY_RISK_PCT = env_float("DCA_RECOVERY_RISK_PCT", 30)
DCA_TRIGGER_ROIS = env_float_list("DCA_TRIGGER_ROIS", [25, 50, 80, 120])
DCA_TRIGGER_MODE = os.getenv(
    "DCA_TRIGGER_MODE",
    "adaptive_hybrid"
).strip().lower()

if DCA_TRIGGER_MODE not in ("static_roi", "adaptive_hybrid"):
    DCA_TRIGGER_MODE = "static_roi"

DCA_MAX_ADVERSE_ROI = env_float("DCA_MAX_ADVERSE_ROI", 150)
DCA_MIN_SECONDS_BETWEEN_ORDERS = env_int("DCA_MIN_SECONDS_BETWEEN_ORDERS", 3600)
DCA_MIN_PRICE_GAP_ROI = env_float("DCA_MIN_PRICE_GAP_ROI", 8)
DCA_STATE_LOCK_TIMEOUT_SECONDS = env_float("DCA_STATE_LOCK_TIMEOUT_SECONDS", 10)
DCA_PENDING_TIMEOUT_SECONDS = env_int("DCA_PENDING_TIMEOUT_SECONDS", 300)
DCA_REQUIRE_TREND_CONFIRMATION = env_bool("DCA_REQUIRE_TREND_CONFIRMATION", "True")
DCA_REPRICE_TP_AFTER_FILL = env_bool("DCA_REPRICE_TP_AFTER_FILL", "True")
DCA_FIXED_RISK_ENABLED = env_bool("DCA_FIXED_RISK_ENABLED", "True")
DCA_REQUIRE_HARD_STOP = env_bool("DCA_REQUIRE_HARD_STOP", "True")
DCA_MIN_HARD_STOP_BUFFER_ROI = env_float(
    "DCA_MIN_HARD_STOP_BUFFER_ROI",
    5,
)
DCA_RECOVERY_CONFIRMATION_ENABLED = env_bool(
    "DCA_RECOVERY_CONFIRMATION_ENABLED",
    "True",
)
DCA_RECOVERY_TREND_ONLY = env_bool("DCA_RECOVERY_TREND_ONLY", "True")
DCA_RECOVERY_REQUIRE_DATA = env_bool(
    "DCA_RECOVERY_REQUIRE_DATA",
    "True",
)
DCA_RECOVERY_REQUIRE_BOTH_TIMEFRAMES = env_bool(
    "DCA_RECOVERY_REQUIRE_BOTH_TIMEFRAMES",
    "True",
)
DCA_RECOVERY_MIN_REBOUND_ROI = env_float(
    "DCA_RECOVERY_MIN_REBOUND_ROI",
    5,
)
DCA_RECOVERY_ARM_TIMEOUT_MINUTES = env_float(
    "DCA_RECOVERY_ARM_TIMEOUT_MINUTES",
    240,
)
DCA_RECOVERY_EXTREME_PERSIST_STEP_ROI = env_float(
    "DCA_RECOVERY_EXTREME_PERSIST_STEP_ROI",
    1,
)
DCA_TP_MODE = os.getenv("DCA_TP_MODE", "structure").strip().lower()
DCA_TP_ROI = env_float("DCA_TP_ROI", STRUCTURE_TP_FALLBACK_ROI)
DCA_WEBSOCKET_ENABLED = env_bool("DCA_WEBSOCKET_ENABLED", "False")
DCA_WEBSOCKET_FAST_MARK_PRICE = env_bool("DCA_WEBSOCKET_FAST_MARK_PRICE", "True")
DCA_WEBSOCKET_WATCHDOG_ENABLED = env_bool(
    "DCA_WEBSOCKET_WATCHDOG_ENABLED",
    "True"
)
DCA_WEBSOCKET_STALE_SECONDS = env_float("DCA_WEBSOCKET_STALE_SECONDS", 45)
DCA_WEBSOCKET_WATCHDOG_INTERVAL_SECONDS = env_float(
    "DCA_WEBSOCKET_WATCHDOG_INTERVAL_SECONDS",
    10
)
DCA_WEBSOCKET_RESTART_COOLDOWN_SECONDS = env_float(
    "DCA_WEBSOCKET_RESTART_COOLDOWN_SECONDS",
    30
)
DCA_SCAN_WHEN_WEBSOCKET_ENABLED = env_bool(
    "DCA_SCAN_WHEN_WEBSOCKET_ENABLED",
    "False"
)
DCA_STRUCTURE_LEVEL_ENABLED = env_bool("DCA_STRUCTURE_LEVEL_ENABLED", "True")
DCA_STRUCTURE_MIN_SCORE = env_float("DCA_STRUCTURE_MIN_SCORE", 2.0)
DCA_STRUCTURE_MAX_DISTANCE_ATR = env_float("DCA_STRUCTURE_MAX_DISTANCE_ATR", 0.6)
DCA_STRUCTURE_MAX_DISTANCE_ROI = env_float("DCA_STRUCTURE_MAX_DISTANCE_ROI", 6)
DCA_STRUCTURE_REQUIRE_REACTION = env_bool("DCA_STRUCTURE_REQUIRE_REACTION", "True")
DCA_STRUCTURE_REACTION_LOOKBACK = env_int("DCA_STRUCTURE_REACTION_LOOKBACK", 3)
DCA_STRUCTURE_REACTION_MIN_BODY_ATR = env_float(
    "DCA_STRUCTURE_REACTION_MIN_BODY_ATR",
    0.05
)
DCA_STRUCTURE_REACTION_CLOSE_POSITION = env_float(
    "DCA_STRUCTURE_REACTION_CLOSE_POSITION",
    0.55
)
DCA_STRICT_GUARD_ENABLED = env_bool("DCA_STRICT_GUARD_ENABLED", "True")
DCA_STRICT_GUARD_REQUIRE_DATA = env_bool("DCA_STRICT_GUARD_REQUIRE_DATA", "True")
DCA_STRICT_GUARD_APPLY_TO_REVERSAL_ONLY = env_bool(
    "DCA_STRICT_GUARD_APPLY_TO_REVERSAL_ONLY",
    "False"
)
DCA_STRICT_GUARD_MAX_PRESSURE_SCORE = env_float(
    "DCA_STRICT_GUARD_MAX_PRESSURE_SCORE",
    5.5
)
DCA_STRICT_GUARD_HARD_PRESSURE_SCORE = env_float(
    "DCA_STRICT_GUARD_HARD_PRESSURE_SCORE",
    7.0
)
DCA_STRICT_GUARD_MIN_RECOVERY_SCORE = env_float(
    "DCA_STRICT_GUARD_MIN_RECOVERY_SCORE",
    2.5
)
DCA_STRICT_GUARD_REVERSAL_MIN_RECOVERY_SCORE = env_float(
    "DCA_STRICT_GUARD_REVERSAL_MIN_RECOVERY_SCORE",
    3.25
)
DCA_STRICT_GUARD_REVERSAL_FIRST_DCA_MIN_RECOVERY_SCORE = env_float(
    "DCA_STRICT_GUARD_REVERSAL_FIRST_DCA_MIN_RECOVERY_SCORE",
    4.25
)
DCA_STRICT_GUARD_REVERSAL_FIRST_DCA_MAX_PRESSURE_SCORE = env_float(
    "DCA_STRICT_GUARD_REVERSAL_FIRST_DCA_MAX_PRESSURE_SCORE",
    4.75
)
DCA_STRICT_GUARD_STRUCTURE_CHECK_ENABLED = env_bool(
    "DCA_STRICT_GUARD_STRUCTURE_CHECK_ENABLED",
    "True"
)
DCA_STRICT_GUARD_BLOCK_REVERSAL_ON_NO_STRUCTURE = env_bool(
    "DCA_STRICT_GUARD_BLOCK_REVERSAL_ON_NO_STRUCTURE",
    "True"
)
DCA_STRICT_GUARD_BLOCK_TREND_ON_NO_STRUCTURE = env_bool(
    "DCA_STRICT_GUARD_BLOCK_TREND_ON_NO_STRUCTURE",
    "False"
)
DCA_STRICT_GUARD_MAX_ADVERSE_ROI = env_float(
    "DCA_STRICT_GUARD_MAX_ADVERSE_ROI",
    0
)
DCA_ADAPTIVE_ATR_MULTIPLIERS = env_float_list(
    "DCA_ADAPTIVE_ATR_MULTIPLIERS",
    [1.0, 1.25, 1.5, 1.75]
)
DCA_ADAPTIVE_REQUIRE_STRUCTURE = env_bool(
    "DCA_ADAPTIVE_REQUIRE_STRUCTURE",
    "True"
)
DCA_ADAPTIVE_REQUIRE_RECOVERY = env_bool(
    "DCA_ADAPTIVE_REQUIRE_RECOVERY",
    "True"
)
DCA_ADAPTIVE_MIN_RECOVERY_SCORE = env_float(
    "DCA_ADAPTIVE_MIN_RECOVERY_SCORE",
    2.5
)
DCA_ADAPTIVE_REVERSAL_MIN_RECOVERY_SCORE = env_float(
    "DCA_ADAPTIVE_REVERSAL_MIN_RECOVERY_SCORE",
    3.5
)
DCA_ADAPTIVE_RECOVERY_STEP_PER_LEVEL = env_float(
    "DCA_ADAPTIVE_RECOVERY_STEP_PER_LEVEL",
    0.25
)
DCA_ADAPTIVE_BLOCK_TREND_THESIS_INVALIDATION = env_bool(
    "DCA_ADAPTIVE_BLOCK_TREND_THESIS_INVALIDATION",
    "True"
)
DCA_ADAPTIVE_THESIS_MIN_ADX = env_float(
    "DCA_ADAPTIVE_THESIS_MIN_ADX",
    18
)
DCA_MIN_TP_ROOM_ROI = env_float("DCA_MIN_TP_ROOM_ROI", ENTRY_MIN_TP_ROOM_ROI)
DCA_FORCE_REMAINING_ENABLED = env_bool("DCA_FORCE_REMAINING_ENABLED", "False")
DCA_FORCE_REMAINING_ROI = env_float("DCA_FORCE_REMAINING_ROI", 100)

# Default long-term behavior is no exchange SL. The adverse-zone support or
# resistance check is used for trade quality, not as a mandatory stop order.
SL_ENABLED = env_bool("SL_ENABLED", "False")
MAX_SL_ROI = env_float("MAX_SL_ROI", 50)
TREND_SL_ENABLED = env_bool(
    "TREND_SL_ENABLED",
    os.getenv("SL_ENABLED", "False")
)
REVERSAL_SL_ENABLED = env_bool(
    "REVERSAL_SL_ENABLED",
    "True"
)
TREND_MAX_SL_ROI = env_float("TREND_MAX_SL_ROI", MAX_SL_ROI)
REVERSAL_MAX_SL_ROI = env_float("REVERSAL_MAX_SL_ROI", 80)
REVERSAL_PROFIT_PROTECTION_ENABLED = env_bool(
    "REVERSAL_PROFIT_PROTECTION_ENABLED",
    "True"
)
REVERSAL_PROFIT_PROTECTION_TRIGGER_ROI = env_float(
    "REVERSAL_PROFIT_PROTECTION_TRIGGER_ROI",
    12
)
REVERSAL_PROFIT_PROTECTION_LOCK_ROI = env_float(
    "REVERSAL_PROFIT_PROTECTION_LOCK_ROI",
    3
)
REVERSAL_PROFIT_PROTECTION_RETRACE_PCT = env_float(
    "REVERSAL_PROFIT_PROTECTION_RETRACE_PCT",
    50
)
REVERSAL_PROFIT_PEAK_PERSIST_STEP_ROI = env_float(
    "REVERSAL_PROFIT_PEAK_PERSIST_STEP_ROI",
    2
)
TREND_PROFIT_PROTECTION_ENABLED = env_bool(
    "TREND_PROFIT_PROTECTION_ENABLED",
    "True"
)
TREND_PROFIT_PROTECTION_TRIGGER_ROI = env_float(
    "TREND_PROFIT_PROTECTION_TRIGGER_ROI",
    15
)
TREND_PROFIT_PROTECTION_LOCK_ROI = env_float(
    "TREND_PROFIT_PROTECTION_LOCK_ROI",
    5
)
TREND_PROFIT_PROTECTION_RETRACE_PCT = env_float(
    "TREND_PROFIT_PROTECTION_RETRACE_PCT",
    45
)
TREND_PROFIT_PEAK_PERSIST_STEP_ROI = env_float(
    "TREND_PROFIT_PEAK_PERSIST_STEP_ROI",
    1
)
PROFIT_EXIT_PENDING_RETRY_SECONDS = env_float(
    "PROFIT_EXIT_PENDING_RETRY_SECONDS",
    60,
)
SL_INVALID_FAILS_PROTECTION_ORDER = env_bool(
    "SL_INVALID_FAILS_PROTECTION_ORDER",
    "False"
)
HARD_STOP_RECONCILE_ENABLED = env_bool(
    "HARD_STOP_RECONCILE_ENABLED",
    "True",
)
HARD_STOP_RECONCILE_LEGACY_POSITIONS = env_bool(
    "HARD_STOP_RECONCILE_LEGACY_POSITIONS",
    "False",
)
HARD_STOP_STARTUP_FAIL_CLOSE = env_bool(
    "HARD_STOP_STARTUP_FAIL_CLOSE",
    "True",
)

LONG_TERM_SIGNAL_THRESHOLD = env_float("LONG_TERM_SIGNAL_THRESHOLD", 100)
LONG_TERM_MIN_SIGNAL_EDGE = env_float("LONG_TERM_MIN_SIGNAL_EDGE", 6)
LONG_TERM_CONFIDENCE_MAX_SCORE = env_float("LONG_TERM_CONFIDENCE_MAX_SCORE", 42)
SIGNAL_MODULE_GATES_ENABLED = env_bool("SIGNAL_MODULE_GATES_ENABLED", "True")
SIGNAL_MIN_TREND_SCORE = env_float("SIGNAL_MIN_TREND_SCORE", 7.5)
SIGNAL_MIN_CONFIRM_SCORE = env_float("SIGNAL_MIN_CONFIRM_SCORE", 7.5)
SIGNAL_MIN_ENTRY_SCORE = env_float("SIGNAL_MIN_ENTRY_SCORE", 4.25)
SIGNAL_MIN_QUALITY_SCORE = env_float("SIGNAL_MIN_QUALITY_SCORE", 0.25)
SIGNAL_MIN_REGIME_SCORE = env_float("SIGNAL_MIN_REGIME_SCORE", -1.25)
TREND_TIMING_RESCUE_ENABLED = env_bool(
    "TREND_TIMING_RESCUE_ENABLED",
    "True"
)
TREND_TIMING_RESCUE_MIN_CONFIDENCE = env_float(
    "TREND_TIMING_RESCUE_MIN_CONFIDENCE",
    100
)
TREND_TIMING_RESCUE_SCORE_TOLERANCE = env_float(
    "TREND_TIMING_RESCUE_SCORE_TOLERANCE",
    0.5
)
TREND_TIMING_RESCUE_MIN_QUALITY_SCORE = env_float(
    "TREND_TIMING_RESCUE_MIN_QUALITY_SCORE",
    1.0
)
TREND_TIMING_RESCUE_MIN_REGIME_SCORE = env_float(
    "TREND_TIMING_RESCUE_MIN_REGIME_SCORE",
    -1.25
)
TREND_TIMING_RESCUE_REQUIRE_FUTURES = env_bool(
    "TREND_TIMING_RESCUE_REQUIRE_FUTURES",
    "True"
)
TREND_TIMING_RESCUE_MIN_FUTURES_SCORE = env_float(
    "TREND_TIMING_RESCUE_MIN_FUTURES_SCORE",
    0
)
TREND_TIMING_RESCUE_REQUIRE_BOTH_LIVE_TIMEFRAMES = env_bool(
    "TREND_TIMING_RESCUE_REQUIRE_BOTH_LIVE_TIMEFRAMES",
    "True"
)
CONTINUATION_PULLBACK_ENABLED = env_bool(
    "CONTINUATION_PULLBACK_ENABLED",
    "True"
)
CONTINUATION_PULLBACK_MIN_CONFIDENCE = env_float(
    "CONTINUATION_PULLBACK_MIN_CONFIDENCE",
    100
)
CONTINUATION_PULLBACK_MIN_TREND_SCORE = env_float(
    "CONTINUATION_PULLBACK_MIN_TREND_SCORE",
    8
)
CONTINUATION_PULLBACK_MIN_CONFIRM_SCORE = env_float(
    "CONTINUATION_PULLBACK_MIN_CONFIRM_SCORE",
    8
)
CONTINUATION_PULLBACK_MIN_ENTRY_SCORE = env_float(
    "CONTINUATION_PULLBACK_MIN_ENTRY_SCORE",
    2.5
)
CONTINUATION_PULLBACK_MIN_QUALITY_SCORE = env_float(
    "CONTINUATION_PULLBACK_MIN_QUALITY_SCORE",
    1
)
CONTINUATION_PULLBACK_MIN_REGIME_SCORE = env_float(
    "CONTINUATION_PULLBACK_MIN_REGIME_SCORE",
    0
)
CONTINUATION_PULLBACK_MAX_EMA20_DISTANCE_ATR = env_float(
    "CONTINUATION_PULLBACK_MAX_EMA20_DISTANCE_ATR",
    0.75
)
CONTINUATION_PULLBACK_EMA20_TOUCH_ATR = env_float(
    "CONTINUATION_PULLBACK_EMA20_TOUCH_ATR",
    0.20
)
CONTINUATION_PULLBACK_EMA50_BREAK_BUFFER_ATR = env_float(
    "CONTINUATION_PULLBACK_EMA50_BREAK_BUFFER_ATR",
    0.15
)
CONTINUATION_PULLBACK_STRUCTURE_LOOKBACK = env_int(
    "CONTINUATION_PULLBACK_STRUCTURE_LOOKBACK",
    8
)
CONTINUATION_PULLBACK_STRUCTURE_BREAK_BUFFER_ATR = env_float(
    "CONTINUATION_PULLBACK_STRUCTURE_BREAK_BUFFER_ATR",
    0.15
)
CONTINUATION_PULLBACK_BUY_MIN_RSI = env_float(
    "CONTINUATION_PULLBACK_BUY_MIN_RSI",
    44
)
CONTINUATION_PULLBACK_BUY_MAX_RSI = env_float(
    "CONTINUATION_PULLBACK_BUY_MAX_RSI",
    70
)
CONTINUATION_PULLBACK_SELL_MIN_RSI = env_float(
    "CONTINUATION_PULLBACK_SELL_MIN_RSI",
    30
)
CONTINUATION_PULLBACK_SELL_MAX_RSI = env_float(
    "CONTINUATION_PULLBACK_SELL_MAX_RSI",
    56
)
CONTINUATION_PULLBACK_MAX_VOLUME_MULT = env_float(
    "CONTINUATION_PULLBACK_MAX_VOLUME_MULT",
    1.35
)
CONTINUATION_PULLBACK_MAX_CANDLE_ATR = env_float(
    "CONTINUATION_PULLBACK_MAX_CANDLE_ATR",
    1.25
)
CONTINUATION_PULLBACK_REQUIRE_FUTURES = env_bool(
    "CONTINUATION_PULLBACK_REQUIRE_FUTURES",
    "True"
)
CONTINUATION_PULLBACK_MIN_FUTURES_SCORE = env_float(
    "CONTINUATION_PULLBACK_MIN_FUTURES_SCORE",
    0.5
)
CONTINUATION_PULLBACK_REQUIRE_BOTH_LIVE_TIMEFRAMES = env_bool(
    "CONTINUATION_PULLBACK_REQUIRE_BOTH_LIVE_TIMEFRAMES",
    "True"
)
# Range/mean-reversion fade at a validated boundary during a sideways
# (low-ADX) regime. Ships disabled: RANGE_REVERSION_ENABLED defaults False
# and the position pool defaults to 0 capacity, so flipping ENABLED alone
# does not let it trade until slots are explicitly allocated below.
RANGE_REVERSION_ENABLED = env_bool("RANGE_REVERSION_ENABLED", "False")
RANGE_REVERSION_SIGNAL_THRESHOLD = env_float(
    "RANGE_REVERSION_SIGNAL_THRESHOLD",
    70
)
RANGE_REVERSION_CONFIDENCE_MAX_SCORE = env_float(
    "RANGE_REVERSION_CONFIDENCE_MAX_SCORE",
    12
)
RANGE_REVERSION_MIN_SIGNAL_EDGE = env_float(
    "RANGE_REVERSION_MIN_SIGNAL_EDGE",
    0
)
RANGE_REVERSION_MAX_LEVEL_ADVERSE_ROI = env_float(
    "RANGE_REVERSION_MAX_LEVEL_ADVERSE_ROI",
    8.0
)
RANGE_REVERSION_MIN_LEVEL_SCORE = env_float(
    "RANGE_REVERSION_MIN_LEVEL_SCORE",
    3.0
)
RANGE_REVERSION_RSI_OVERSOLD = env_float("RANGE_REVERSION_RSI_OVERSOLD", 32)
RANGE_REVERSION_RSI_OVERBOUGHT = env_float("RANGE_REVERSION_RSI_OVERBOUGHT", 68)
RANGE_REVERSION_MIN_QUALITY_SCORE = env_float(
    "RANGE_REVERSION_MIN_QUALITY_SCORE",
    0.0
)
RANGE_REVERSION_MIN_CONFIRM_SCORE = env_float(
    "RANGE_REVERSION_MIN_CONFIRM_SCORE",
    -3.0
)
RANGE_REVERSION_SL_ENABLED = env_bool("RANGE_REVERSION_SL_ENABLED", "True")
RANGE_REVERSION_MAX_SL_ROI = env_float("RANGE_REVERSION_MAX_SL_ROI", 10.0)
# A range fade targets the opposite boundary, not a trend-sized move -
# ENTRY_MIN_TP_ROOM_ROI's 30% default (tuned for trend) would reject nearly
# every range trade. REVERSAL gets the same kind of override; this mirrors it.
RANGE_REVERSION_MIN_TP_ROOM_ROI = env_float(
    "RANGE_REVERSION_MIN_TP_ROOM_ROI",
    5.0
)
# Own time-exit budget: a range fade should resolve quickly or the sideways
# thesis is questionable. Without these, a range position silently inherited
# TREND's 480-minute window and TREND_TIME_EXIT label (confirmed via backtest:
# the one historical range trade found was closed by this, not its own
# structure TP or SL).
TIME_EXIT_RANGE_REVERSION_ENABLED = env_bool(
    "TIME_EXIT_RANGE_REVERSION_ENABLED",
    "True"
)
TIME_EXIT_RANGE_REVERSION_MINUTES = env_float(
    "TIME_EXIT_RANGE_REVERSION_MINUTES",
    180
)
TIME_EXIT_RANGE_REVERSION_MAX_ROI = env_float(
    "TIME_EXIT_RANGE_REVERSION_MAX_ROI",
    0
)
# evaluate_time_exit_weakness() only checks trend continuation (4h/1d EMA
# alignment, MACD, structure break) - the opposite of what a range fade bets
# on. A range entry is taken *because* the trend looks weak (oversold RSI
# near support), so this trend-weakness gate almost never confirms for this
# route, letting a flat/losing range position run well past its own time
# floor (confirmed via backtest: the one historical range trade held ~10h
# past its 180-minute floor waiting for a "weakness" signal that couldn't
# fire). Route gets its own require-weakness switch instead of inheriting
# TREND's.
TIME_EXIT_RANGE_REVERSION_REQUIRE_WEAKNESS = env_bool(
    "TIME_EXIT_RANGE_REVERSION_REQUIRE_WEAKNESS",
    "False"
)
RANGE_REVERSION_TOTAL_POSITIONS = env_int("RANGE_REVERSION_TOTAL_POSITIONS", 0)
RANGE_REVERSION_BUY_POSITIONS = env_int("RANGE_REVERSION_BUY_POSITIONS", 0)
RANGE_REVERSION_SELL_POSITIONS = env_int("RANGE_REVERSION_SELL_POSITIONS", 0)

REVERSAL_MODE_ENABLED = env_bool("REVERSAL_MODE_ENABLED", "True")
REVERSAL_ENTRY_ENABLED = env_bool("REVERSAL_ENTRY_ENABLED", "True")
REVERSAL_SIGNAL_THRESHOLD = env_float("REVERSAL_SIGNAL_THRESHOLD", 80)
REVERSAL_CONFIDENCE_MAX_SCORE = env_float("REVERSAL_CONFIDENCE_MAX_SCORE", 34)
REVERSAL_MIN_CONFIRM_SCORE = env_float("REVERSAL_MIN_CONFIRM_SCORE", 8)
REVERSAL_MIN_ENTRY_SCORE = env_float("REVERSAL_MIN_ENTRY_SCORE", 5)
REVERSAL_MIN_QUALITY_SCORE = env_float("REVERSAL_MIN_QUALITY_SCORE", 1.0)
REVERSAL_MIN_SMC_SCORE = env_float("REVERSAL_MIN_SMC_SCORE", 1.25)
REVERSAL_MIN_REGIME_SCORE = env_float("REVERSAL_MIN_REGIME_SCORE", -1.0)
REVERSAL_MAX_TREND_SCORE = env_float("REVERSAL_MAX_TREND_SCORE", 7.5)
REVERSAL_MIN_SIGNAL_EDGE = env_float("REVERSAL_MIN_SIGNAL_EDGE", 0)
REVERSAL_IGNORE_OPPOSITE_TREND_CONFIDENCE = env_bool(
    "REVERSAL_IGNORE_OPPOSITE_TREND_CONFIDENCE",
    "True"
)
REVERSAL_LOG_BLOCKED_MIN_CONFIDENCE = env_float(
    "REVERSAL_LOG_BLOCKED_MIN_CONFIDENCE",
    55
)
REVERSAL_MOMENTUM_SCORE_ENABLED = env_bool(
    "REVERSAL_MOMENTUM_SCORE_ENABLED",
    "True"
)
REVERSAL_MOMENTUM_SIGNAL_THRESHOLD = env_float(
    "REVERSAL_MOMENTUM_SIGNAL_THRESHOLD",
    75
)
REVERSAL_MOMENTUM_MIN_SCORE = env_float("REVERSAL_MOMENTUM_MIN_SCORE", 4.5)
REVERSAL_MOMENTUM_MIN_CONFIRM_SCORE = env_float(
    "REVERSAL_MOMENTUM_MIN_CONFIRM_SCORE",
    5
)
REVERSAL_MOMENTUM_MIN_ENTRY_SCORE = env_float(
    "REVERSAL_MOMENTUM_MIN_ENTRY_SCORE",
    4
)
REVERSAL_MOMENTUM_MIN_QUALITY_SCORE = env_float(
    "REVERSAL_MOMENTUM_MIN_QUALITY_SCORE",
    0.75
)
REVERSAL_MOMENTUM_MIN_REGIME_SCORE = env_float(
    "REVERSAL_MOMENTUM_MIN_REGIME_SCORE",
    -1.0
)
REVERSAL_MOMENTUM_LOOKBACK = env_int("REVERSAL_MOMENTUM_LOOKBACK", 3)
REVERSAL_MOMENTUM_MIN_CANDLES = env_int("REVERSAL_MOMENTUM_MIN_CANDLES", 2)
REVERSAL_MOMENTUM_EMA_TOLERANCE_PCT = env_float(
    "REVERSAL_MOMENTUM_EMA_TOLERANCE_PCT",
    0.25
)
REVERSAL_MOMENTUM_MIN_BODY_ATR = env_float(
    "REVERSAL_MOMENTUM_MIN_BODY_ATR",
    0.25
)
REVERSAL_MOMENTUM_MIN_CLOSE_POSITION = env_float(
    "REVERSAL_MOMENTUM_MIN_CLOSE_POSITION",
    0.60
)
REVERSAL_MIN_TP_ROOM_ROI = env_float(
    "REVERSAL_MIN_TP_ROOM_ROI",
    ENTRY_MIN_TP_ROOM_ROI
)
REVERSAL_REQUIRE_SMC = env_bool("REVERSAL_REQUIRE_SMC", "True")
REVERSAL_ALLOW_MOMENTUM_WITHOUT_SMC = env_bool(
    "REVERSAL_ALLOW_MOMENTUM_WITHOUT_SMC",
    "False"
)
REVERSAL_REQUIRE_COUNTER_TREND = env_bool(
    "REVERSAL_REQUIRE_COUNTER_TREND",
    "True"
)
REVERSAL_EXTRA_CONFIRMATION_ENABLED = env_bool(
    "REVERSAL_EXTRA_CONFIRMATION_ENABLED",
    "True"
)
REVERSAL_MIN_CONFIRMATION_POINTS = env_float(
    "REVERSAL_MIN_CONFIRMATION_POINTS",
    6
)
REVERSAL_STRONG_PRESSURE_MIN_CONFIRMATION_POINTS = env_float(
    "REVERSAL_STRONG_PRESSURE_MIN_CONFIRMATION_POINTS",
    7
)
REVERSAL_CONFIRMATION_STRONG_PRESSURE_SCORE = env_float(
    "REVERSAL_CONFIRMATION_STRONG_PRESSURE_SCORE",
    5.0
)
REVERSAL_REQUIRE_MOMENTUM_OR_RECOVERY = env_bool(
    "REVERSAL_REQUIRE_MOMENTUM_OR_RECOVERY",
    "True"
)
REVERSAL_REQUIRE_FUTURES_CONFIRMATION = env_bool(
    "REVERSAL_REQUIRE_FUTURES_CONFIRMATION",
    "True"
)
REVERSAL_MIN_FUTURES_SCORE = env_float(
    "REVERSAL_MIN_FUTURES_SCORE",
    0.5
)
REVERSAL_REQUIRE_BOTH_LIVE_TIMEFRAMES = env_bool(
    "REVERSAL_REQUIRE_BOTH_LIVE_TIMEFRAMES",
    "True"
)
TREND_EXHAUSTION_GUARD_ENABLED = env_bool(
    "TREND_EXHAUSTION_GUARD_ENABLED",
    "True"
)
TREND_EXHAUSTION_MIN_WARNING_POINTS = env_float(
    "TREND_EXHAUSTION_MIN_WARNING_POINTS",
    4
)
TREND_EXHAUSTION_STRONG_PRESSURE_MIN_WARNING_POINTS = env_float(
    "TREND_EXHAUSTION_STRONG_PRESSURE_MIN_WARNING_POINTS",
    5
)
TREND_EXHAUSTION_MIN_REVERSAL_CONFIDENCE = env_float(
    "TREND_EXHAUSTION_MIN_REVERSAL_CONFIDENCE",
    65
)
TREND_EXHAUSTION_MIN_RECOVERY_SCORE = env_float(
    "TREND_EXHAUSTION_MIN_RECOVERY_SCORE",
    2.5
)
TREND_EXHAUSTION_REQUIRE_DIRECTIONAL_TRIGGER = env_bool(
    "TREND_EXHAUSTION_REQUIRE_DIRECTIONAL_TRIGGER",
    "True"
)
TREND_EXHAUSTION_FUTURES_VETO_ENABLED = env_bool(
    "TREND_EXHAUSTION_FUTURES_VETO_ENABLED",
    "True"
)
TREND_EXHAUSTION_FUTURES_SUPPORT_SCORE = env_float(
    "TREND_EXHAUSTION_FUTURES_SUPPORT_SCORE",
    0.5
)
REVERSAL_INVALIDATION_ENABLED = env_bool("REVERSAL_INVALIDATION_ENABLED", "True")
REVERSAL_INVALIDATION_MIN_PRESSURE_SCORE = env_float(
    "REVERSAL_INVALIDATION_MIN_PRESSURE_SCORE",
    5.5
)
REVERSAL_INVALIDATION_HARD_PRESSURE_SCORE = env_float(
    "REVERSAL_INVALIDATION_HARD_PRESSURE_SCORE",
    7.0
)
REVERSAL_INVALIDATION_MIN_RECOVERY_SCORE = env_float(
    "REVERSAL_INVALIDATION_MIN_RECOVERY_SCORE",
    3.0
)
REVERSAL_INVALIDATION_MIN_ADX = env_float("REVERSAL_INVALIDATION_MIN_ADX", 18)
REVERSAL_REQUIRE_RECOVERY_CONFIRMATION = env_bool(
    "REVERSAL_REQUIRE_RECOVERY_CONFIRMATION",
    "True"
)
REVERSAL_RECOVERY_MIN_SCORE = env_float("REVERSAL_RECOVERY_MIN_SCORE", 3.75)
REVERSAL_RECOVERY_STRONG_PRESSURE_SCORE = env_float(
    "REVERSAL_RECOVERY_STRONG_PRESSURE_SCORE",
    4.75
)
REVERSAL_RECOVERY_STRONG_PRESSURE_MIN_SCORE = env_float(
    "REVERSAL_RECOVERY_STRONG_PRESSURE_MIN_SCORE",
    4.5
)
LONG_TERM_ADVERSE_ZONE_CHECK_ENABLED = env_bool(
    "LONG_TERM_ADVERSE_ZONE_CHECK_ENABLED",
    "True"
)
LONG_TERM_MAX_ADVERSE_ROI = env_float("LONG_TERM_MAX_ADVERSE_ROI", 50)
ADVERSE_REVERSAL_LEVEL_CHECK_ENABLED = env_bool(
    "ADVERSE_REVERSAL_LEVEL_CHECK_ENABLED",
    os.getenv("LONG_TERM_ADVERSE_ZONE_CHECK_ENABLED", "True")
)
ADVERSE_REVERSAL_MAX_ROI = env_float(
    "ADVERSE_REVERSAL_MAX_ROI",
    LONG_TERM_MAX_ADVERSE_ROI
)
ADVERSE_REVERSAL_TIMEFRAME = os.getenv("ADVERSE_REVERSAL_TIMEFRAME", "1d")
ADVERSE_REVERSAL_MIN_SCORE = env_float(
    "ADVERSE_REVERSAL_MIN_SCORE",
    2.5
)
ADVERSE_REVERSAL_USE_1D_ONLY = env_bool(
    "ADVERSE_REVERSAL_USE_1D_ONLY",
    "True"
)
ADVERSE_REVERSAL_INCLUDE_RANGE = env_bool(
    "ADVERSE_REVERSAL_INCLUDE_RANGE",
    "True"
)
ADVERSE_REVERSAL_INCLUDE_EMA = env_bool(
    "ADVERSE_REVERSAL_INCLUDE_EMA",
    "True"
)
LONG_TERM_SR_LOOKBACK = env_int("LONG_TERM_SR_LOOKBACK", 160)
LONG_TERM_SR_MIN_TOUCHES = env_int("LONG_TERM_SR_MIN_TOUCHES", 2)
LONG_TERM_SR_MIN_SCORE = env_float("LONG_TERM_SR_MIN_SCORE", 2.5)
LONG_TERM_SR_TOLERANCE_PCT = env_float("LONG_TERM_SR_TOLERANCE_PCT", 1.0)
LONG_TERM_SR_ATR_TOLERANCE = env_float("LONG_TERM_SR_ATR_TOLERANCE", 0.75)
LONG_TERM_SR_MAX_TOLERANCE_PCT = env_float("LONG_TERM_SR_MAX_TOLERANCE_PCT", 1.25)
LONG_TERM_SR_SWING = env_int("LONG_TERM_SR_SWING", 3)
LONG_TERM_SR_TOUCH_MIN_GAP = env_int("LONG_TERM_SR_TOUCH_MIN_GAP", 5)
LONG_TERM_SR_REACTION_BONUS = env_float("LONG_TERM_SR_REACTION_BONUS", 1.0)
LONG_TERM_SR_VOLUME_BONUS = env_float("LONG_TERM_SR_VOLUME_BONUS", 0.5)
LONG_TERM_SR_CONFLUENCE_BONUS = env_float("LONG_TERM_SR_CONFLUENCE_BONUS", 0.75)
LONG_TERM_SR_RECENT_BREAK_PENALTY = env_float(
    "LONG_TERM_SR_RECENT_BREAK_PENALTY",
    1.5
)
LONG_TERM_SR_RANGE_MIN_TOUCHES = env_int("LONG_TERM_SR_RANGE_MIN_TOUCHES", 2)
LONG_TERM_SR_EMA_MIN_RESPECTS = env_int("LONG_TERM_SR_EMA_MIN_RESPECTS", 2)
LONG_TERM_ENTRY_MAX_EMA_DISTANCE_PCT = env_float(
    "LONG_TERM_ENTRY_MAX_EMA_DISTANCE_PCT",
    6.0
)
LONG_TERM_MIN_ADX = env_float("LONG_TERM_MIN_ADX", 14)
LONG_TERM_BTC_CORR_THRESHOLD = env_float("LONG_TERM_BTC_CORR_THRESHOLD", 0.65)
EMA_GAP_FILTER_ENABLED = env_bool("EMA_GAP_FILTER_ENABLED", "True")
MIN_EMA20_EMA50_GAP_PCT = env_float("MIN_EMA20_EMA50_GAP_PCT", 0.03)
MIN_EMA50_EMA200_GAP_PCT = env_float("MIN_EMA50_EMA200_GAP_PCT", 0.05)
MAX_EMA20_EMA50_GAP_PCT = env_float("MAX_EMA20_EMA50_GAP_PCT", 0)
MAX_EMA50_EMA200_GAP_PCT = env_float("MAX_EMA50_EMA200_GAP_PCT", 0)
EMA_GAP_SCORE_BONUS = env_float("EMA_GAP_SCORE_BONUS", 0.75)
EMA_GAP_SCORE_PENALTY = env_float("EMA_GAP_SCORE_PENALTY", 0.5)
MAX_SIGNAL_EMA20_DISTANCE_PCT = env_float("MAX_SIGNAL_EMA20_DISTANCE_PCT", 1.0)
MAX_ENTRY_EMA20_DISTANCE_PCT = env_float("MAX_ENTRY_EMA20_DISTANCE_PCT", 1.0)
MAX_SIGNAL_CANDLE_ATR = env_float("MAX_SIGNAL_CANDLE_ATR", 1.8)
MIN_VOLUME_SMA_MULT = env_float("MIN_VOLUME_SMA_MULT", 1.05)
MIN_SIGNAL_BODY_RATIO = env_float("MIN_SIGNAL_BODY_RATIO", 0.16)
MIN_SIGNAL_CLOSE_POSITION = env_float("MIN_SIGNAL_CLOSE_POSITION", 0.50)
MAX_SIGNAL_CLOSE_POSITION = env_float("MAX_SIGNAL_CLOSE_POSITION", 0.88)
SIGNAL_WICK_FILTER_ENABLED = env_bool("SIGNAL_WICK_FILTER_ENABLED", "True")
MAX_SIGNAL_REJECTION_WICK_RATIO = env_float(
    "MAX_SIGNAL_REJECTION_WICK_RATIO",
    0.45
)
MIN_SIGNAL_MOMENTUM_ATR = env_float("MIN_SIGNAL_MOMENTUM_ATR", 0.03)
SIDEWAYS_ADX = env_float("SIDEWAYS_ADX", 15)
TRENDING_ADX = env_float("TRENDING_ADX", 25)
MAX_LATE_ENTRY_ATR = env_float("MAX_LATE_ENTRY_ATR", 1.8)
LATE_ENTRY_SCORE_PENALTY = env_float("LATE_ENTRY_SCORE_PENALTY", 2)
LATE_ENTRY_HARD_BLOCK_ENABLED = env_bool("LATE_ENTRY_HARD_BLOCK_ENABLED", "True")
MAX_LATE_ENTRY_HARD_BLOCK_ATR = env_float("MAX_LATE_ENTRY_HARD_BLOCK_ATR", 2.6)
MAX_CHASE_DISTANCE_PCT = env_float("MAX_CHASE_DISTANCE_PCT", 0.55)
BUY_RSI_OVERHEAT = env_float("BUY_RSI_OVERHEAT", 71)
SELL_RSI_OVERHEAT = env_float("SELL_RSI_OVERHEAT", 29)

MAX_TOTAL_POSITIONS = (
    int(os.getenv("MAX_TOTAL_POSITIONS"))
    if os.getenv("MAX_TOTAL_POSITIONS")
    else None
)

MAX_BUY_POSITIONS = (
    int(os.getenv("MAX_BUY_POSITIONS"))
    if os.getenv("MAX_BUY_POSITIONS")
    else None
)

MAX_SELL_POSITIONS = (
    int(os.getenv("MAX_SELL_POSITIONS"))
    if os.getenv("MAX_SELL_POSITIONS")
    else None
)

REVERSAL_EXTRA_TOTAL_POSITIONS = env_int("REVERSAL_EXTRA_TOTAL_POSITIONS", 0)
REVERSAL_EXTRA_BUY_POSITIONS = env_int("REVERSAL_EXTRA_BUY_POSITIONS", 0)
REVERSAL_EXTRA_SELL_POSITIONS = env_int("REVERSAL_EXTRA_SELL_POSITIONS", 0)
TP1_EXTRA_SLOTS_ENABLED = env_bool("TP1_EXTRA_SLOTS_ENABLED", "False")
TP1_EXTRA_TOTAL_POSITIONS = env_int("TP1_EXTRA_TOTAL_POSITIONS", 0)
TP1_EXTRA_BUY_POSITIONS = env_int("TP1_EXTRA_BUY_POSITIONS", 0)
TP1_EXTRA_SELL_POSITIONS = env_int("TP1_EXTRA_SELL_POSITIONS", 0)

TESTNET = env_bool("TESTNET", "False")

BACKTEST_SYMBOLS = [
    symbol.strip()
    for symbol in os.getenv("BACKTEST_SYMBOLS", "").split(",")
    if symbol.strip()
]
BACKTEST_START = os.getenv("BACKTEST_START", "")
BACKTEST_END = os.getenv("BACKTEST_END", "")
BACKTEST_DATA_DIR = os.getenv("BACKTEST_DATA_DIR", "backtest_data")
BACKTEST_RESULTS_DIR = os.getenv("BACKTEST_RESULTS_DIR", "backtest_results")
BACKTEST_DOWNLOAD_DATA = env_bool("BACKTEST_DOWNLOAD_DATA", "False")
BACKTEST_FORCE_DOWNLOAD = env_bool("BACKTEST_FORCE_DOWNLOAD", "False")
BACKTEST_DOWNLOAD_SLEEP_SECONDS = env_float(
    "BACKTEST_DOWNLOAD_SLEEP_SECONDS",
    0.2
)
BACKTEST_MAX_SYMBOLS = env_int("BACKTEST_MAX_SYMBOLS", 10)
BACKTEST_WARMUP_CANDLES = env_int("BACKTEST_WARMUP_CANDLES", 260)
BACKTEST_MAX_HOLD_CANDLES = env_int("BACKTEST_MAX_HOLD_CANDLES", 240)
BACKTEST_SIGNAL_STEP_CANDLES = env_int("BACKTEST_SIGNAL_STEP_CANDLES", 4)
BACKTEST_PROGRESS_EVERY_CANDLES = env_int("BACKTEST_PROGRESS_EVERY_CANDLES", 500)
BACKTEST_FAST_MODE = env_bool("BACKTEST_FAST_MODE", "False")
BACKTEST_SLICE_MAX_ROWS = env_int("BACKTEST_SLICE_MAX_ROWS", 420)
BACKTEST_USE_BTC_CONTEXT = env_bool("BACKTEST_USE_BTC_CONTEXT", "True")
BACKTEST_INITIAL_BALANCE = env_float("BACKTEST_INITIAL_BALANCE", 1000)
BACKTEST_MARGIN_PER_TRADE = env_float("BACKTEST_MARGIN_PER_TRADE", 0)
BACKTEST_FEE_RATE = env_float("BACKTEST_FEE_RATE", 0.0004)
BACKTEST_SLIPPAGE_PCT = env_float("BACKTEST_SLIPPAGE_PCT", 0.02)
BACKTEST_MULTI_TP_ENABLED = env_bool(
    "BACKTEST_MULTI_TP_ENABLED",
    "True" if MULTI_TP_ENABLED else "False"
)
BACKTEST_USE_DCA = env_bool(
    "BACKTEST_USE_DCA",
    "True" if DCA_ENABLED else "False"
)
BACKTEST_ONE_POSITION_PER_SYMBOL = env_bool(
    "BACKTEST_ONE_POSITION_PER_SYMBOL",
    "True"
)
BACKTEST_APPLY_POSITION_LIMITS = env_bool(
    "BACKTEST_APPLY_POSITION_LIMITS",
    "True"
)
BACKTEST_EXIT_TIMEFRAME = os.getenv("BACKTEST_EXIT_TIMEFRAME", ENTRY_TIMEFRAME)
BACKTEST_CONFIRMATION_TYPES = [
    item.strip().upper()
    for item in os.getenv("BACKTEST_CONFIRMATION_TYPES", "").split(",")
    if item.strip()
]
